apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-config" (include "common.names.fullname" .) }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: agent
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  argfile.yml: |
    label: {{ include "common.names.fullname" . | quote }}
    inbound-transport:
      - [http, 0.0.0.0, {{ .Values.service.ports.http }}]
      {{- if .Values.websockets.enabled }}
      - [ws, 0.0.0.0, {{ .Values.service.ports.ws }}]
      {{- end }}
    outbound-transport:
      - http
      {{- if .Values.websockets.enabled }}
      - ws
      {{- end }}
    endpoint:
      - {{ include "acapy.agent.url" . | quote }}
      {{- if .Values.websockets.enabled }}
      - {{ include "acapy.agent.wsUrl" . | quote }}
      {{- end }}
    admin:
      - 0.0.0.0
      - {{ .Values.service.ports.admin }}
    {{- include "common.tplvalues.render" ( dict "value" (index .Values "argfile.yml") "context" $) | nindent 4 }}
    wallet-storage-config: {{ include "acapy.walletStorageConfig" . }}
  {{- if index .Values "ledgers.yml" }}
  ledgers.yml: |
    {{- include "common.tplvalues.render" ( dict "value" (index .Values "ledgers.yml") "context" $) | nindent 4 }}
  {{- end }}
  {{- if index .Values "plugin-config.yml" }}
  plugin-config.yml: |
    {{- include "common.tplvalues.render" ( dict "value" (index .Values "plugin-config.yml") "context" $) | nindent 4 }}
  {{- end }}
