apiVersion: v2
name: vc-authn-oidc
description: A Helm chart to deploy ACAPy VC-AuthN on OpenShift
type: application

appVersion: "2.3.0"
version: 0.4.3

maintainers:
  - email: emiliano.sune@quartech.com
    name: esune
    url: https://github.com/esune
  - email: ivan.polchenko@quartech.com
    name: i5okie
    url: https://github.com/i5okie

# Charts the vc-authn-oidc service depends on
dependencies:
  - name: acapy
    version: 0.2.1
    repository: https://openwallet-foundation.github.io/helm-charts/
  - name: mongodb
    version: 16.4.1
    repository: "https://charts.bitnami.com/bitnami"
  - name: common
    repository: "https://charts.bitnami.com/bitnami"
    tags:
      - bitnami-common
    version: 2.x.x
