environment:
  - name: AGENT_PORT
    value: "3000"
  - name: AGENT_NAME
    value: Mediator
  - name: WALLET_NAME
    value: mediator-wallet
  - name: AGENT_ENDPOINTS
    value: "http://example.com,wss://example.com"
  - name: LOG_LEVEL
    value: "2"
  - name: PICKUP_TYPE
    value: Null
  - name: PICKUP_STRATEGY
    value: DirectDelivery
  - name: PICKUP_SETTINGS
    value: "{}"

autoscaling:
  enabled: false
